# Generated by Django 4.1.7 on 2023-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='github_profile',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='my_website',
            field=models.CharField(blank='True', max_length=255, null='True'),
        ),
    ]
