# Generated by Django 4.1.7 on 2023-03-20 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='candidate_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='facebook_profile',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='mobile',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
    ]
