# Generated by Django 4.1.7 on 2023-04-03 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_candidateinfo_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='candidate_email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+@[a-zA-Z0-9]+\\.[a-z]{1,3}$', message='Enter Valid E-mail')]),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='candidate_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z]+[a-zA-Z]$', message='Enter only Alphabets')]),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Enter only Numbers')]),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='objective',
            field=models.CharField(blank='True', max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-z]{2,4}$', message='Enter Valid E-mail')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z\\s]+', message='Enter only Alphabets')]),
        ),
    ]
