# Generated by Django 4.1.7 on 2023-04-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_candidateinfo_candidate_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_or_institute_name', models.CharField(max_length=50)),
                ('learn_skills', models.CharField(max_length=50)),
                ('duration_in_month', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidateinfo')),
            ],
        ),
    ]
